### ISSUE TITLE
Set type automatically

### ISSUE THREAD

**Issue by arnoudplantinga** [WillemSleegers/tidystats-v0.3#1]
If "type" refers to the type of the test, shall we add it automatically? For example, for tidystats.htest I use `type = "t-test"`.

**Comment by WillemSleegers** [comment]
Sounds good; but we should also have a parameter indicating whether the test is an hypothesis test, manipulation check test, or something else. What shall we use for that?

**Comment by arnoudplantinga** [comment]
Yeah, maybe we should keep `type` for that parameter, and add a variable `test` or `modeltype` to indicate what kind of test was performed?
