### ISSUE TITLE
Combine functions

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#11]
Shall we combine multiple functions in 1 script? For example, we can combine all the report functions in 1 script, as well as all the tidystats functions.

**Comment by arnoudplantinga** [comment]
Yeah, at some point I think we could combine, e.g., all the `tidystats` and `report` functions. At the moment, I have a mild preference for keeping them separate.

**Comment by WillemSleegers** [comment]
Alright, closing for now.
