### ISSUE TITLE
Rename effect_size to cohens_d?

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#13]
I think effect_size is too broad a term for it. For example, with a correlation, the effect size is the actual estimate itself. There are also multiple kinds of effect sizes, so might be easier to just be specific in terms of what kind of effect size the column represents.

**Comment by arnoudplantinga** [comment]
That might create lots of columns. What about one column to identify the kind of effect size (effect_size_measure = "Cohen's _d_") and one for the number itself (effect_size = 0.64)?

**Comment by WillemSleegers** [comment]
That would increase the complexity of retrieving the specific effect size in Markdown documents.

**Comment by arnoudplantinga** [comment]
Done!
