### ISSUE TITLE
Round statistics values already when we add them to the results data frame?

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#14]
Might be better to already take care of the rounding when they are added to the data frame, rather than when we intend to report them in a Markdown document.

**Comment by arnoudplantinga** [comment]
I'd prefer to have as much info as possible in the results data frame. 

First, people might want to round to a different of decimals, and this could lead to errors. E.g., if I round 1.0148 to 3 decimals, I get 1.015, then someone else rounds it to two decimals and gets 1.02, whereas rounding it in one step to 2 decimals would yield 1.01. 

Second, more precise values are more valuable for meta-analyses.

**Comment by WillemSleegers** [comment]
Okay, I agree.
