### ISSUE TITLE
Radical idea: Save results as list of data frames

### ISSUE THREAD

**Issue by arnoudplantinga** [WillemSleegers/tidystats-v0.3#15]
Like this:

    $model1
      estimate statistic    p.value parameter                  method   cohens_d            description
    1    -1.58 -1.860813 0.07939414  17.77647 Welch Two Sample t-test -0.8826937 Test if a t-test works
    
    $model3
       estimate statistic   p.value parameter                               method                 description
    1 0.5711816  1.841083 0.1081731         7 Pearson's product-moment correlation Test if a correlation works

Main advantage: presentation of the results is much nicer, because you don't get lots of columns with `NA`. This allows a lot of flexibility in what you want to save for each type of model. For models with multiple parameters (e.g., linear models), you could create list of data frames. In addition, it's also very easy to select a certain model with `results$model1`. 

If you want to save the results to .csv, you can do something like:

```R
df <- bind_rows(results)
df$identifier <- names(results)
```

To do: 

- [x] `add_stats`
- [x] `new_stats_data_frame`
- [x] `read_stats`
- [x] `write_stats`
- [x] `report_t_test`

**Comment by WillemSleegers** [comment]
I like it.

**Comment by arnoudplantinga** [comment]
I am surprised!

**Comment by arnoudplantinga** [comment]
To do: 

- [x] `add_stats`
- [x] `new_stats_data_frame`
- [x] `read_stats`
- [x] `write_stats`
- [ ] `report.htest`
- [ ] `report.data.frame`
- [ ] `report_t_test`

**Comment by WillemSleegers** [comment]
Completed the to-do list!
