### ISSUE TITLE
Should we keep the `identifier` variable in each data.frame?

### ISSUE THREAD

**Issue by arnoudplantinga** [WillemSleegers/tidystats-v0.3#19]
For example, the results element for a linear regression looks like this:

```R
> results$M6
  identifier       type            method        term   estimate  std_error statistic      p_value                                     description
1         M6 hypothesis Linear regression (Intercept) 14.3763194 6.61998601  2.171654 3.850833e-02 Test whether regression with 1 predictor works.
2         M6 hypothesis Linear regression  complaints  0.7546098 0.09753289  7.736978 1.987682e-08 Test whether regression with 1 predictor works.
```

- Disadvantage: Output is more cluttered, the variable is unnecessary
- Advantage: We don't have to manually add the identifier variable when saving to a `.csv`
- Advantage: We don't have to manually remove the identifier when reading from a `.csv`

**Comment by WillemSleegers** [comment]
I'd say we remove it from the data frame when it's part of the results list, but store it into the data frame when the results are saved to disk.
