### ISSUE TITLE
The current formula Cohen's d is only an estimation

### ISSUE THREAD

**Issue by arnoudplantinga** [WillemSleegers/tidystats-v0.3#21]
And a pretty rough one. This means that we should either (1) forget about Cohen's _d_, or (2) figure out another way to add results to the results list.

**Comment by arnoudplantinga** [comment]
We could also do both? Give both the options to (1) specify a model, you don't get Cohen's _d_, or (2) specify a formula and dataset, you get Cohen's _d_ with a confidence interval.

**Comment by WillemSleegers** [comment]
I think that if we want to add more output to `t.test()`, we need to write our own t_test function. Let's not make it part of, say, our `add_stats()` function.

**Comment by WillemSleegers** [comment]
It's not the point of the package to produce better stats output of stats functions.

**Comment by WillemSleegers** [comment]
I removed the cohens_d output for now.
