### ISSUE TITLE
Should the tidy_stats function accept the model or the output of summary(model)?

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#40]
Some stats function, such as `manova()` accept specific arguments only while doing the `summary()` function. 

For example: 

```
model <- summary(manova(cbind(Sepal.Length, Petal.Length) ~ Species, data = iris), test = "Roy")`
```

How to best solve this issue?

**Comment by WillemSleegers** [comment]
Add an argument to `add_stats()` to optionally supply a list of arguments?

**Comment by WillemSleegers** [comment]
For example:

```
results <- list()

model <- manova(cbind(Sepal.Length, Petal.Length) ~ Species, data = iris))`

results <- add_stats(results, model, args = list(test = "Roy"))

**Comment by WillemSleegers** [comment]
Or call it summary_args?

**Comment by arnoudplantinga** [comment]
I like that! Maybe `args_summary` would make a little more sense, but I'm not sure.

**Comment by WillemSleegers** [comment]
Added an argument called `args` that can be used for use cases like this.
