### ISSUE TITLE
Test descriptives functions

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#42]
I have added several functions to deal with descriptives, rather than statistical models.

You can now use the function `descriptives()` for continuous data, and `frequencies()` for count data. You may turn the output of these functions into a tidy data frame using `tidy_descriptives()`, which is done for you when you add the output to a list using `add_descriptives()`. 

Note that I have switched the arguments in `add_descriptives()`, it first expects the output, then the data frame to add it to.

It would be nice if some people could help me test these functions out and let me know what you think of it.

**UPDATE**:

I changed a few things. First, `descriptives()` has been renamed to `describe()`. This masks the same function for the `psych` package, but meh, describe is a better name. 

Second, I got rid of `frequencies()` by combining it with the `describe()` function. `describe()` now checks what kind of variable is being supplied and depending on that it either provides statistics suitable for numeric variables (e.g., mean, sd, etc.) or frequency statistics (e.g., n, percentages).

Now, there are some issues though. I'll provide some examples below using the `mpg` data set.

**1 numeric variable, no groups**:

Code:
`describe(mpg, cyl`:

Output: 
```
# A tibble: 1 x 11
    var missing     n     M    SD    SE   min   max range median  mode
  <chr>   <int> <int> <dbl> <dbl> <dbl> <int> <int> <int>  <dbl> <int>
1   cty       0   234    17   4.3  0.28     9    35    26     17    18
```

**1 numeric variable, 1 group**:

Code:
`describe(mpg, cty, year)`

Output: 
```
# A tibble: 2 x 13
    var    by group missing     n     M    SD    SE   min   max range median  mode
* <chr> <chr> <chr>   <int> <int> <dbl> <dbl> <dbl> <int> <int> <int>  <int> <int>
1   cty  year  1999       0   117    17   4.5  0.41    11    35    24     17    18
2   cty  year  2008       0   117    17   4.1  0.37     9    28    19     17    13
```

**1 numeric variable, 2 groups**:

Code:
`describe(mpg, cty, year, cyl)`

Output:
```
# A tibble: 7 x 13
    var       by  group missing     n     M    SD    SE   min   max range median  mode
* <chr>    <chr>  <chr>   <int> <int> <dbl> <dbl> <dbl> <int> <int> <int>  <dbl> <int>
1   cty year-cyl 1999-4       0    45    21  4.24  0.63    15    35    20     19    21
2   cty year-cyl 1999-6       0    45    16  1.67  0.25    13    19     6     16    18
3   cty year-cyl 1999-8       0    27    12  1.65  0.32    11    16     5     11    11
4   cty year-cyl 2008-4       0    36    21  2.29  0.38    17    28    11     21    21
5   cty year-cyl 2008-5       0     4    20  0.58  0.29    20    21     1     20    21
6   cty year-cyl 2008-6       0    34    16  1.91  0.33    11    19     8     17    17
7   cty year-cyl 2008-8       0    43    13  1.88  0.29     9    16     7     13    13
```

Some questions I have:
- As you can see in the 1 numeric variable, 2 groups example, groups are put together in the `by` column and `group` column. This makes tidying it easier, but I should probably write this function without having the tidying in mind and simply make it a good describe function, irrespective of how we can tidy it later. Because the function is part of the tidystats package, we will always be able to tidy it (since we know how it is structured). What do you think?

```
# A tibble: 7 x 13
    var by_1 by_2 group_1 group_2  missing     n     M    SD    SE   min   max range median  mode
* <chr> <chr> <chr> <chr> <chr>   <int> <int> <dbl> <dbl> <dbl> <int> <int> <int>  <dbl> <int>
1   cty year cyl 1999 4       0    45    21  4.24  0.63    15    35    20     19    21
2   cty year cyl 1999 6       0    45    16  1.67  0.25    13    19     6     16    18
3   cty year cyl 1999 8       0    27    12  1.65  0.32    11    16     5     11    11
4   cty year cyl 2008 4       0    36    21  2.29  0.38    17    28    11     21    21
5   cty year cyl 2008 5       0     4    20  0.58  0.29    20    21     1     20    21
6   cty year cyl 2008 6       0    34    16  1.91  0.33    11    19     8     17    17
7   cty year cyl 2008 8       0    43    13  1.88  0.29     9    16     7     13    13
```

**Comment by lakenp** [comment]
Maybe include an argument overwrite (default = F) weather add descriptive should overwrite the descriptives already in the list under that identifier?

**Comment by ghost** [comment]
It seems to gather descriptives one time too often? 


```
library(devtools)
# install_github("WillemSleegers/tidystats")
library(tidystats)
library(tidyverse)

iris.descriptives <- list()

descriptives(iris, Sepal.Length, Species) -> 
  Species.descriptives

Species.descriptives %>% 
  tidy_descriptives() %>%
  add_descriptives(list = iris.descriptives,
                   identifier = "Species") -> 
  iris.descriptives


iris.descriptives %>%
  .$Species %>%
  filter(var == "Sepal.Length") %>%
  filter(group == "versicolor")
```

**Comment by WillemSleegers** [comment]
Yup, because you don't need to do `tidy_descriptives()`. `add_descriptives()` calls that function, so it's more of an 'under the hood' function.

**Comment by WillemSleegers** [comment]
Closing this issue because I have completely redesigned the way creating and adding descriptives works.

**Comment by ghost** [comment]
Lekker bezig!

Op 21 sep. 2017 01:43 schreef "WillemSleegers" <notifications@github.com>:

**Comment by WillemSleegers** [comment]
Check out the new README: https://github.com/WillemSleegers/tidystats <https://github.com/WillemSleegers/tidystats>
