### ISSUE TITLE
Create a good way to add confidence intervals to regression output

### ISSUE THREAD

**Issue by arnoudplantinga** [WillemSleegers/tidystats-v0.3#50]
Two options:

- [x] Create a function to replace `lm`
- [x] Create a function to merge confidence intervals with regression results

Let's do both?

**Comment by WillemSleegers** [comment]
What would be a good name for an `lm` replacement function?

**Comment by arnoudplantinga** [comment]
`tidy_lm`? Or `lmt`? Also depends on what output it gives, maybe. If the output is tidy already, `tidy_lm` would work. If it's more of a summary, I'd be more for something like `lmt`.

**Comment by WillemSleegers** [comment]
I suppose we still want to be able run `summary()` on it...

**Comment by WillemSleegers** [comment]
Implemented the merge function, it's called `add_stats_to_model()`.

**Comment by WillemSleegers** [comment]
I also created a new version of `lm()` in a branch called 'tidy_lm'.
