### ISSUE TITLE
To do for our new lm function

### ISSUE THREAD

**Issue by arnoudplantinga** [WillemSleegers/tidystats-v0.3#51]
- [x] Add standardized coefficients
- [x] Add effect size estimates for the coefficients
    - [x] Eta squared
    - [x] Partial eta squared
- [x] Find an awesome name (`awesome_lm`?)

**Comment by WillemSleegers** [comment]
I checked out effect sizes for regression, and eta squared and partial eta squared don't really fit with regression (they do with GLM).

In fact, I think b and beta coefficients are sufficient estimates of an effect size. 

We could, however, consider adding Cohen's f.

**Comment by mjbsp** [comment]
GLM and regression are essentially the same thing. But, regardless, for standard regression standardized slopes and r^2 of model would be pretty typical of most effect size reporting.

**Comment by WillemSleegers** [comment]
True, but at least in SPSS the default effect size output for GLMs is eta squared; while it is not for regression. I'm actually not that familiar with `glm()` in R, but I suppose it works the same as `lm()`, which means also there eta-squared won't fit very well. There should probably be an `eta_squared()` function, accepting regression output, that produces those effect sizes. 

Anyhow, standardized regression coefficients have been added, and r^2 is already part of the output. =)

**Comment by WillemSleegers** [comment]
Going for `awesome_lm()` (I really cannot come up with anything better), and I'm forgetting about the extra effect sizes. They probably fit something else better (e.g., `anova()`).
