### ISSUE TITLE
Report does not work for self-created statistics

### ISSUE THREAD

**Issue by mjbsp** [WillemSleegers/tidystats-v0.3#54]
I created my own code to save results of Cohen d from effsize package. I tried to use report to report them. Relevant results tibble, Rmd code, and error message included.

<img width="470" alt="screen shot 2017-11-25 at 09 51 52" src="https://user-images.githubusercontent.com/25500769/33229000-77f9dd5c-d1c6-11e7-9c74-cdc4c9e2bc25.png">
<img width="390" alt="screen shot 2017-11-25 at 09 52 06" src="https://user-images.githubusercontent.com/25500769/33229001-7812eda6-d1c6-11e7-8262-70821d4ecd7d.png">
<img width="804" alt="screen shot 2017-11-25 at 09 52 23" src="https://user-images.githubusercontent.com/25500769/33229002-782a7f98-d1c6-11e7-9c1a-8249d2bd8ab5.png">

A general method for making custom functions to save and then report stats would be useful.

**Comment by WillemSleegers** [comment]
I improved the `report()` functions and it should support that now.

If you install the package directly from github (using devtools), then you should be able to test it out. Can you let me know whether it works?

**Comment by mjbsp** [comment]
It did not work, but there is a new error message.
![capture](https://user-images.githubusercontent.com/25500769/33260357-dd6a94e8-d35f-11e7-9a55-f80b5a7abde7.PNG)

Note that this code does work
```
`r filter(results$btn.d.maintext, statistic == "d")`
```

**Comment by mjbsp** [comment]
My prior comment forgot the quotes about the d, but even after adding it did not work as expected.

**Comment by WillemSleegers** [comment]
Should work now. =)

**Comment by mjbsp** [comment]
Agreed. It works now. Thanks!
