### ISSUE TITLE
Separate lists for statistics and descriptives

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#59]
In an earlier version I distinguished between a stats list for the output of statistical tests and descriptives. They are structured quite differently, so combining them together (which IS possible), results in extra columns and some additional complexity in adding results to the stats list (via `add_stats()`). 

I think it may be cleaner to just have an `add_stats()` and an `add_descriptives()`, to create two lists. 

What do you think?

**Comment by arnoudplantinga** [comment]
I think I still prefer having only 1 list. Adding a second list of results means I also have to save a second list, load a second list, publish a second list with my paper, etc. I think that adds more complexity than adding some columns to the existing list.

**Comment by WillemSleegers** [comment]
Alright, I agree.
