### ISSUE TITLE
Better error message when trying to report a nonexistent result

### ISSUE THREAD

**Issue by arnoudplantinga** [WillemSleegers/tidystats-v0.3#60]
When I try to report a result with a nonexistent identifier, I get the following error:

    Error in if (grepl("t-test", method)) { : argument is of length zero

We should provide a more helpful error message.

**Comment by WillemSleegers** [comment]
That's weird since I have this code in it:

```
# Check whether the identifier exists
  if (!identifier %in% names(results)) {
    stop("Identifier not found.")
  }
```

What was the code you used?

**Comment by arnoudplantinga** [comment]
It works in the latest version
