### ISSUE TITLE
Better default identifier

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#62]
We can improve the default identifier by using the variable name containing the output of the statistical model. In other words, simply use the variable name of the first argument.

Example:
```
# Run regression model
M11_PPBS_age <- lm(pseudo_profound_bullshit ~ age, data = data)

# Inspect results
summary(M11_PPBS_age)

# Add to tidystats list
results <- add_stats(M11_PPBS_age, results)
```

**Comment by arnoudplantinga** [comment]
Yes, great idea!

**Comment by WillemSleegers** [comment]
Implemented it.
