### ISSUE TITLE
Possible solution for statistical tests that do not return identifiable output

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#65]
Some statistical functions do not return identifiable output. For example, `confint()` or **ppcor**'s `pcor.test()` return a simple matrix or data.frame, as demonstrated below:

```
fit <- lm(100/mpg ~ disp + hp + wt + am, data = mtcars)
confint <- confint(fit)

class(confint)
```
```
[1] "matrix"
```

This is a challenge for tidystats because it's not possible to figure out how to tidy the output. One possible solution is to tidy it yourself and then supply it to `add_stats()`. Because `add_stats()` also accepts pre-tidied data frames, it works.

An alternative is that tidystats provides very specific tidy functions, like `tidy_stats_confint()`, which can be used to first tidy the output and then add it via `add_stats()`.

I'm now thinking we can also do it immediately via `add_stats()`. We can add an argument to `add_stats()` called 'class', which `add_stats()` will then use to run the proper `tidy_stats()` function. The documentation of `add_stats()` can show which classes are supported.

Example:

```
# Old:
confint_tidy <- tidy_stats_confint(confint)
results <- add_stats(results, confint_tidy, identifier = "confint")

# Or:
results <- add_stats(results, tidy_stats_confint(confint), identifier = "confint")

# New:
results <- add_stats(results, confint, class = "confint")
```

What do you think?

**Comment by arnoudplantinga** [comment]
I like it! This way, we don't have to write a ton of custom functions, and it's probably easier to understand.

We should also come up with a good error message for when the class is missing and `add_stats` is unable to guess it.

**Comment by WillemSleegers** [comment]
So one complexity is that `add_stats()` also accepts data frames. If you give the output of `confint()`, `add_stats()` will simply add it to the list, even though it is not in a tidy format. I think I have a heuristic check to see whether the data frame is indeed tidy (e.g., check whether it is has a statistic and value column), but it's not foolproof. 

Maybe with this solution we could get rid of the data frame option, or have `add_stats()` only accept data frames when a specific class is provided (e.g., `class = "custom"`).

**Comment by arnoudplantinga** [comment]
Or just give a warning? _You added a data.frame to your results list_.

**Comment by WillemSleegers** [comment]
Implemented this. =)
