### ISSUE TITLE
Remove statistics argument from add_stats?

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats-v0.3#68]
I was thinking that the statistics argument does not make a lot of sense, and is potentially annoying.

The statistics argument can be used to only save some of the statistics, by providing a vector of the statistics you actually want to add.

Philosophical problem: This goes against saving all your statistical results.
Pragmatic problem: If someone decides not to save, say, the t-value of a t-test, then the report function will not report it correctly.

Perhaps we can just remove it?

**Comment by arnoudplantinga** [comment]
I don't think I would ever use it (hard drive space is not really a problem), so I'd be fine with that!

**Comment by WillemSleegers** [comment]
Removed it.
